[package]
name = "egui-winit"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
chrono = "0.4"
egui = "0.8"
egui_demo_lib = "0.8"
egui_wgpu_backend = "0.4"
egui_winit_platform = "0.4"
epaint = "0.8"
epi = "0.8"
env_logger = "0.7"
log = "0.4"
pixels = { path = "../.." }
winit = "0.24"
winit_input_helper = "0.9"
