[package]
name = "invaders"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
publish = false

[dependencies]
byteorder = "1.3.4"
env_logger = "0.7.1"
getrandom = "0.1.14"
gilrs = "0.7.4"
log = { version = "0.4.8", features = [ "release_max_level_warn" ] }
pixels = { path = "../.." }
randomize = "3.0.1"
simple-invaders = { path = "simple-invaders" }
winit = "0.22.0"
winit_input_helper = "0.6.0"
