[package]
name = "invaders"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
byteorder = "1.3.4"
env_logger = "0.7.1"
getrandom = "0.1.14"
gilrs = "0.7.4"
log = "0.4.8"
pixels = { path = "../.." }
randomize = "3.0.1"
simple-invaders = { path = "simple-invaders" }
winit = "0.22.0"
winit_input_helper = "0.6.0"
