[package]
name = "simple-invaders"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"

[dependencies]
line_drawing = "0.8"
pcx = "0.2"
rand_core = { version = "0.5", features = ["std"] }
