[package]
name = "simple-invaders"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"

[dependencies]
arrayvec = "0.5"
line_drawing = "0.8"
pcx = "0.2"
randomize = "3.0"

[dev-dependencies]
byteorder = "1.3"
getrandom = "0.1"
